version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typescript-introduction-web
    volumes: 
      - ".:/app"
    ports:
      - "0.0.0.0:8000:1234"